export const ADMIN_SHOE_FORM_TEXT = {
    ADD_TITLE: 'Add Shoe',
    EDIT_TITLE: 'Edit Shoe',
    BRAND_LABEL: 'Brand',
    BRAND_PLACEHOLDER: 'Brand name',
    COST_LABEL: 'Cost',
    COST_PLACEHOLDER: '0.00',
    SIZES_LABEL: 'Available Sizes',
    IMAGE_LABEL: 'Image (optional)',
    IMAGE_URL_PLACEHOLDER: 'Paste an image URL',
    OR_LABEL: 'or',
    CHOOSE_PHOTO: 'Choose Photo',
    CHANGE_PHOTO: 'Change Photo',
    SAVE: 'Save',
    DELETE: 'Delete Shoe',
    DELETE_CONFIRM_TITLE: 'Delete Shoe',
    DELETE_CONFIRM_MESSAGE: 'Are you sure you want to delete this shoe? This will also remove it from any cart it\'s in.',
    CANCEL: 'Cancel',
}
